project:
  type: website
  output-dir: docs

website:
  title: "Joanna R. Pepin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://jrpepin.github.io/joannapepin.github.io/CV.pdf
        text: CV
      - press.qmd
      - href: https://github.com/jrpepin
        text: Code
      - teaching.qmd

# supplying just one theme ("flatly")
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
