project:
  type: website
  output-dir: docs

website:
  title: "Joanna R. Pepin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: CV.pdf
        text: "Vita"
        icon: file-pdf
      - press.qmd
      - text: "Code"
        menu: 
          - text: "Repositories"
            href: https://github.com/jrpepin
      - text: Teaching
        menu:
          - text: "Overview"
            href: teaching.qmd
          - text: "Slides (example)"
            file: "soc214h/Slides/01.1 A Sociology of the Family.qmd"
      - blog.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
resources:
  - CNAME