project:
  type: website
  output-dir: docs

website:
  title: "Joanna R. Pepin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - press.qmd

# supplying just one theme ("flatly")
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
