project:
  type: website
  output-dir: docs

website:
  title: "Joanna R. Pepin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: CV.pdf
        text: "Vita"
        icon: file-pdf
      - press.qmd
      - text: "Code"
        menu: 
          - text: "Repositories"
            href: https://github.com/jrpepin
 #         - text: "Stata"
 #           href: stata.qmd
      - teaching.qmd
        menu:
          - text: "Slides"
            href: https://github.com/jrpepin/joannapepin.github.io/blob/main/docs/soc214h/Slides/01.1%20A%20Sociology%20of%20the%20Family.html
      - blog.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
resources:
  - CNAME