project:
  type: website
  output-dir: docs

website:
  title: "Joanna R. Pepin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: CV.pdf
        text: "Vita"
        icon: file-pdf
      - press.qmd
      - text: "Code"
        menu: 
          - text: "Repositories"
            href: https://github.com/jrpepin
          - text: "test"
            href: "https://www.google.com/"
 #        - text: "Stata"
 #          href: stata.qmd
      - text: teaching
        menu:
          - text: "Overview"
            href: teaching.qmd

      - blog.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
resources:
  - CNAME