project:
  type: website
  output-dir: docs

website:
  title: "Joanna R. Pepin"
  site-url: https://joannapepin.com
  description: "Pepin blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: CV.pdf
        text: "Vita"
        icon: file-pdf
      - press.qmd
      - text: "Code"
        menu: 
          - text: "Repositories"
            href: https://github.com/jrpepin
          - text: "ATUS Tutorial"
            href: https://jrpepin.github.io/IPUMS-American-Time-Use-Surveys-in-R/
      - href: teaching.qmd
        text: Teaching
      - text: Blog
        href: posts.qmd
      - icon: bluesky
        href: https://bsky.app/profile/joannapepin.bsky.social

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-in-header: verification-follow_it-NLNC3eVTqV4kqX78ArsD.html

editor: visual
resources:
  - CNAME
