---
title: "Teaching"
---

## Courses

Social Statistics \| SOC294 \| Spring 2023 [syllabus](https://rpubs.com/jpepin/soc294_SP23){target="_blank"}

Sociology of Families \| SOC313 \| Fall 2020 [syllabus](https://rpubs.com/jpepin/soc313_FA2020){target="_blank"}

## Instructor Resources

### [Family Sociology Video Resource List](https://docs.google.com/document/d/14_ugDceLx_pwgOtFHHHZ676r3sGrb1VB/edit?usp=sharing&ouid=116976022537856309917&rtpof=true&sd=true){target="_blank"}

List of free videos that correspond with the chapters in the textbook: [The Family- Diversity, Inequality, and Social Change](https://wwnorton.com/books/9780393537314){target="_blank"}

### [Fact Check Assignment](https://drive.google.com/file/d/1dpwhP6Rmp7-HzgWVefn0OdbFCb0MzmW7/view){target="_blank"}

The objective for this assignment is for students to learn how to critically evaluate evidence in the media. It can be adapted for any content course and students pick their own sub-topic of interest to generate personal interest and motivation.

### [Flipped Quiz Assignment](https://drive.google.com/file/d/1xjCFUnl2qOh2XWUQPTGOvWyHBIZ3Rxh_/view){target="_blank"}

Students learn how to determine key content in course material. They also collaboratively create a study review guide by sharing their created quiz questions with classmates.
